### ISSUE TITLE
[cloud-monolith-to-microservices-gke]:

### ISSUE THREAD

**Issue by nishantabanik** [googlecodelabs/monolith-to-microservices#34] opened 2022-01-23 14:41 UTC
The codes are broken.

Both Orders & Products microservice pages are not working.
Kindy make the appropriate changes...

**Comment by verbanicm** [comment] 2022-01-24 20:44
This looks like duplicate of #35, closing this issue

**Closed by verbanicm** 2022-01-24 20:44 UTC
